# wrangler.toml
name = 'tian987'
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = "9dae64a3215040f192a904deaffaef6b"				#KV数据库id
